import { routing } from "@/i18n/routing";
import { cn } from "@/lib/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Anek_Telugu } from "next/font/google";
import { notFound } from "next/navigation";
import "./globals.css";

const AnekTelugu = Anek_Telugu({
  variable: "--font-caption",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diarassouba Mamadou - Software Engineer",
  description: "Online web an mobile developer",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;
  const messages = await getMessages();
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          GeistSans.variable,
          AnekTelugu.variable,
          GeistMono.variable,
          "font-sans bg-background text-foreground"
        )}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

// import { cn } from "@/lib/utils";
// import { GeistSans } from "geist/font/sans";
// import type { Metadata } from "next";
// import { Anek_Telugu } from "next/font/google";
// import "./globals.css";

// const anekTelugu = Anek_Telugu({
//   variable: "--font-caption",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={cn(GeistSans.variable, anekTelugu, "font-sans")}>
//         {children}
//       </body>
//     </html>
//   );
// }
